In [1]:
import torch

/home/rovince/miniconda3/envs/llm_from_scratch/lib/python3.11/site-packages/torch/_subclasses/functional_tensor.py:362: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [2]:
torch.tensor([[1., 2, 3], [5, 4, 2]])

tensor([[1., 2., 3.],
        [5., 4., 2.]])

In [3]:
import torch.nn.functional as F

y = torch.tensor([1.])
x1 = torch.tensor([1.1])
w1 = torch.tensor([0.84])
b = torch.tensor([2.3])

z = x1 * w1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

In [4]:
loss

tensor(0.0390)

In [7]:
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.])
x1 = torch.tensor([1.1])
w1 = torch.tensor([0.84], requires_grad=True)
b = torch.tensor([2.3], requires_grad=True)

z = x1 * w1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)

In [8]:
print(grad_L_w1, grad_L_b)

(tensor([-0.0421]),) (tensor([-0.0383]),)


In [9]:
loss.backward()

In [10]:
print(w1.grad, b.grad)

tensor([-0.0421]) tensor([-0.0383])


In [ ]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, input_units, output_units):
        super().__init__()

        self.layers = torch.nn.Sequential(
            torch.nn.Linear(input_units, 30),
            torch.nn.ReLU(),
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),
            torch.nn.Linear(20, output_units)
        )

    def forward(self, x):
        logits = self.layers(x)
        return logits

In [14]:
model = NeuralNetwork(50, 3)

TypeError: descriptor '__init__' of 'super' object needs an argument