In [1]:
import torch

/home/rovince/miniconda3/envs/llm_from_scratch/lib/python3.11/site-packages/torch/_subclasses/functional_tensor.py:362: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [2]:
torch.tensor([[1., 2, 3], [5, 4, 2]])

tensor([[1., 2., 3.],
        [5., 4., 2.]])

In [3]:
import torch.nn.functional as F

y = torch.tensor([1.])
x1 = torch.tensor([1.1])
w1 = torch.tensor([0.84])
b = torch.tensor([2.3])

z = x1 * w1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

In [4]:
loss

tensor(0.0390)

In [7]:
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.])
x1 = torch.tensor([1.1])
w1 = torch.tensor([0.84], requires_grad=True)
b = torch.tensor([2.3], requires_grad=True)

z = x1 * w1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)

In [8]:
print(grad_L_w1, grad_L_b)

(tensor([-0.0421]),) (tensor([-0.0383]),)


In [9]:
loss.backward()

In [10]:
print(w1.grad, b.grad)

tensor([-0.0421]) tensor([-0.0383])


In [ ]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, input_units, output_units):
        super().__init__()

        self.layers = torch.nn.Sequential(
            torch.nn.Linear(input_units, 30),
            torch.nn.ReLU(),
            torch.nn.Linear(30, 20),
            torch.nn.ReLU(),
            torch.nn.Linear(20, output_units)
        )

    def forward(self, x):
        logits = self.layers(x)
        return logits

In [16]:
model = NeuralNetwork(50, 3)

In [17]:
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


In [27]:
print(sum([p.numel() for p in model.parameters() if p.requires_grad]))
print(len([p for p in model.parameters()]))
print([p for p in model.parameters()])

2213
6
[Parameter containing:
tensor([[-0.1095,  0.0029,  0.1348,  ..., -0.0592,  0.0029, -0.0216],
        [-0.0042, -0.0174, -0.0266,  ...,  0.0568, -0.1037, -0.1119],
        [ 0.0602, -0.1318,  0.1010,  ...,  0.0593, -0.1178,  0.1050],
        ...,
        [ 0.1268,  0.0323,  0.0080,  ..., -0.0580, -0.0322,  0.0252],
        [-0.0638, -0.0708, -0.0468,  ...,  0.0483,  0.0114,  0.0822],
        [-0.0167,  0.1023, -0.1071,  ..., -0.0013,  0.0919, -0.0184]],
       requires_grad=True), Parameter containing:
tensor([ 0.1202,  0.0156,  0.0148,  0.0586,  0.1148,  0.0393,  0.0815, -0.0400,
        -0.0664, -0.0390, -0.0584, -0.0424,  0.0006,  0.1320,  0.0900, -0.0082,
         0.1208,  0.0516,  0.1215,  0.1279,  0.0898, -0.1349, -0.1263,  0.0671,
         0.0668, -0.0861, -0.0628, -0.0319,  0.1322, -0.0844],
       requires_grad=True), Parameter containing:
tensor([[-0.0624,  0.0169, -0.0287, -0.0481, -0.1257, -0.0962, -0.1400, -0.0075,
          0.1372,  0.0344,  0.1743, -0.0420, -0.1277

In [31]:
print(model.layers[0].weight)
print(model.layers[0].weight.shape)
print(model.layers[0].bias)

Parameter containing:
tensor([[-0.1095,  0.0029,  0.1348,  ..., -0.0592,  0.0029, -0.0216],
        [-0.0042, -0.0174, -0.0266,  ...,  0.0568, -0.1037, -0.1119],
        [ 0.0602, -0.1318,  0.1010,  ...,  0.0593, -0.1178,  0.1050],
        ...,
        [ 0.1268,  0.0323,  0.0080,  ..., -0.0580, -0.0322,  0.0252],
        [-0.0638, -0.0708, -0.0468,  ...,  0.0483,  0.0114,  0.0822],
        [-0.0167,  0.1023, -0.1071,  ..., -0.0013,  0.0919, -0.0184]],
       requires_grad=True)
torch.Size([30, 50])
Parameter containing:
tensor([ 0.1202,  0.0156,  0.0148,  0.0586,  0.1148,  0.0393,  0.0815, -0.0400,
        -0.0664, -0.0390, -0.0584, -0.0424,  0.0006,  0.1320,  0.0900, -0.0082,
         0.1208,  0.0516,  0.1215,  0.1279,  0.0898, -0.1349, -0.1263,  0.0671,
         0.0668, -0.0861, -0.0628, -0.0319,  0.1322, -0.0844],
       requires_grad=True)


In [33]:
torch.manual_seed(123)
model = NeuralNetwork(50, 3)
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)


In [34]:
torch.manual_seed(123)
X = torch.rand((1, 50))
out = model(X)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]], grad_fn=<AddmmBackward0>)
